local:
  data:
    input:
      data_dir: ./data/input_data
      charges: Charges_use.csv
      damages: Damages_use.csv
      endorse: Endorse_use.csv
      primary_person: Primary_Person_use.csv
      restrict: Restrict_use.csv
      units: Units_use.csv
    output:
      results_dir: ./data/results
  spark:
